on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: com.rimerosolutions.Entrusted.flatpak
        manifest-path: ${{ github.workspace }}/flatpak/com.rimerosolutions.Entrusted.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: copy-bundle
      shell: bash
      run: |
        mkdir bundle
        cp com.rimerosolutions.Entrusted.flatpak ./bundle/
    - name: upload-flatpak
      uses: actions/upload-artifact@v4
      with:
        name: entrusted-flatpak
        path: ${{ github.workspace }}/bundle

