on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    steps:
    - name: prepare
      shell: bash
      run: |
        sudo apt update && sudo apt -y install flatpak flatpak-builder        
    - uses: actions/checkout@v4
    - name: build-flatpak
      shell: bash
      run: |
        flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir flatpak/com.rimerosolutions.Entrusted.yml

